{% set version = "0.12.1" %}

package:
  name: pythonqwt
  version: {{ version }}

source:
  url: https://github.com/PierreRaybaut/PythonQwt/archive/v{{ version }}.tar.gz
  sha256: a111ff2ee87818d30235849f8fe241d0ed6f19ddd20fdd8bbd289688c4b6cf4c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - numpy >=1.21
    - python >=3.8
    - qtpy >=1.9

test:
  imports:
    - qwt
    - qwt.plot
  requires:
    - pip
    - pyqt
  commands:
    - pip check

about:
  home: https://github.com/PlotPyStack/PythonQwt
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE
  summary: 'PythonQwt: Qt plotting widgets for Python'
  description: |
    The PythonQwt project was initiated to solve -at least temporarily- the
    obsolescence issue of PyQwt (the Python-Qwt C++ bindings library) which is
    no longer maintained. The idea was to translate the original Qwt C++ code
    to Python and then to optimize some parts of the code by writing new
    modules based on NumPy and other libraries.
  doc_url: https://pythonqwt.readthedocs.io
  dev_url: https://github.com/PlotPyStack/PythonQwt

extra:
  recipe-maintainers:
    - beenje
    - marcelotrevisani
