travis:
  secure:
    BINSTAR_TOKEN: OTckySy6fXUny4dafkFG8vj5c6bWvpBPJfmrwcUprIlMsQlIpr7nfPm8pG7cnHBwRSM71o96GG+RPKw6LuavLpLtT12knH/t92vvEvWgdJZvtrGJotXaTia4UedcC1xOe5EIt+uK29gMMzE4/wZZuKUG71iwj+zzLEpdlBBCTT2ieP77jDvdxlZrq7ui8mxY8UC/hhh0a6I88Yf5bj9RldCsVnlGECh5b7OLwHmZouH2rdKED3yBl5qdCAtXJJ1/mkOOHHeDx21sXYGZAHrlO8GZCwUZIe5P2Uz2K+LyRe4c7g/MnqUTPfu8iTe2CImgjWcwPE4Ptjzbj9w9dUIeCOy7IETIGvNJ5J4V6gpxLZVTObii75gcsqkO/Tbq90EHgcw4OroC0dqZZ9+RaLjrNpjY9JlNTUROdCKufW1DKxrME0Sglezk8Ulxjws9fKq8e9G4tmeeKgCZcei1IrZfhm1MmJFkCI77SRthmoEy7mpxSiRLkkIErxNPek7q6/63PgzXNYVQb0BOqgLHEWnKv5HHksCFflHKyt6QSEP0Dag2935IAuduRVkYvCCkxT5fWDLWTwR33iNMB60HVocEt8DCczOtd04c2K6h0OJy9RdkMJmWbqs1oZ8dwvZTHoKQ6VnXLpjIKvLn7ekCyFKi/bRQ2QP5XxrSeVffCUQUwVM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
