travis:
  secure:
    BINSTAR_TOKEN: oK+piWXiKZCZJznB4rxw/Ky4PjE+MRnlyQHKxg5IAyE7cKghGlix7EFGu9ODAJdxHgHwZ1d42CtALMnjd+v9et2EzR6S9miOev4AOd3/hKEXRJSi2JJtyzik8aHdwuI/i4AP1bB9A7B7FgH0o6ha6NVB7CxDP/hagOaJOrydLReqZMa8S/u7jxf4nzueshp/XwK9zQFoL8cBZT9bApF8ZUHbARYCLsgIEwescHG+XYD6/fIrQX5VgA5xaTdEIz2RftJ/2m4FBccGnEyzBy1xM7teZkNuH5g3u1O2gNa+PdrUx+qRH7twIduXNqTow6p/a/GsH5P41iBvrfWA15Ciwc7KPiwDrQxQAo8T9EwuEt6GqP0UyjUeNKTiiYDkFWgTfyj6U8js4f5DPJpvz3DIkIwKh6SIvtq38NEyYQSNi9yaTHA+aPsTFaEkL/2aNJYjVpk8JlAIrFRHgCaAE2ckntX7ut/b7pZr2L8pCyqS2iJsaMs9cD8KGp2uPUEK8H4mNDjCZvvK3/4JGnQ/zPhZsdVMCikf/cLfup04AmUd5yskVEgwkujEqnWYcXLparF6waJswiifd8v372Bx1RHMYyJmUbQgLNESUUnAyd9tQ0+waZJB1ZDnS0wt62kYCUYLSytsjxl6UMXwedOQF/23nObQOJ6lQgJ/UD+e0dRvJl8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
